# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               MIRC
tagline:             'MIRC - DSI'
description:         'Resource page for MIRC - DSI, Bangalore'
url:                 http://mirc-dsi.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sairam Geethanath
  url:               sairam.geethanath@dayanandasagar.edu
  email:             sairam.geethanath@dayanandasagar.edu

# Custom vars
version:             1.0.0
